export default [
    {
      id: 1,
      name: "Sophia Johnson",
      rating: "5",
      comment: "An absolutely amazing experience! The rides were fantastic, and the staff was incredibly friendly.",
      profileImage: require("../assets/images/dataImages/reviews/sophiaJohnson.png"),
    },
    {
      id: 2,
      name: "Liam Brown",
      rating: "4",
      comment: "Great atmosphere and fun for the whole family. The kids loved it!",
      profileImage: require("../assets/images/dataImages/reviews/liamBrown.png"),
    },
    {
      id: 3,
      name: "Noah Wilson",
      rating: "5",
      comment: "Best amusement park ever! The roller coasters were thrilling, and the overall experience was worth every penny.",
      profileImage: require("../assets/images/dataImages/reviews/noahWilson.png"),
    },
    {
      id: 4,
      name: "Olivia Moore",
      rating: "4",
      comment: "We had a great time. The kids enjoyed the rides, and the staff was very accommodating.",
      profileImage: require("../assets/images/dataImages/reviews/oliviaMoore.png"),
    },
    {
      id: 5,
      name: "Ava Anderson",
      rating: "5",
      comment: "Such a magical experience! Everything was well-organized, and the attractions were top-notch.",
      profileImage: require("../assets/images/dataImages/reviews/avaAnderson.png"),
    },
    {
      id: 6,
      name: "Isabella Thompson",
      rating: "4",
      comment: "Very enjoyable experience! The water park section was particularly fun.",
      profileImage: require("../assets/images/dataImages/reviews/isabellaThompson.png"),
    },
    {
      id: 7,
      name: "Mia Harris",
      rating: "5",
      comment: "An unforgettable day! The family had a blast, and we can't wait to come back.",
      profileImage: require("../assets/images/dataImages/reviews/miaHarris.png"),
    },
    {
      id: 8,
      name: "Benjamin Clark",
      rating: "4",
      comment: "Nice park with plenty of attractions. The family had a great time.",
      profileImage: require("../assets/images/dataImages/reviews/benjaminClark.png"),
    },
    {
      id: 9,
      name: "Charlotte Lewis",
      rating: "5",
      comment: "We loved every minute! The staff was amazing, and the rides were unforgettable.",
      profileImage: require("../assets/images/dataImages/reviews/charlotteLewis.png"),
    },
    {
      id: 10,
      name: "Amelia Hall",
      rating: "4",
      comment: "A fun day out! The kids particularly enjoyed the themed areas.",
      profileImage: require("../assets/images/dataImages/reviews/ameliaHall.png"),
    },
    {
      id: 11,
      name: "Harper Young",
      rating: "5",
      comment: "A magical place! We enjoyed every moment and will definitely return.",
      profileImage: require("../assets/images/dataImages/reviews/harperYoung.png"),
    },
    {
      id: 12,
      name: "Henry Hernandez",
      rating: "4",
      comment: "Good variety of attractions and very family-friendly. A perfect place for a weekend getaway.",
      profileImage: require("../assets/images/dataImages/reviews/henryHernandez.png"),
    },
    {
      id: 13,
      name: "Evelyn King",
      rating: "5",
      comment: "A perfect day out! Everything was fantastic, from the rides to the food.",
      profileImage: require("../assets/images/dataImages/reviews/evelynKing.png"),
    },
    {
      id: 14,
      name: "Ella Lopez",
      rating: "5",
      comment: "Loved the themed zones! It was like stepping into a fantasy world.",
      profileImage: require("../assets/images/dataImages/reviews/ellaLopez.png"),
    },
  ];
  