export default [
  {
    id: 1,
    name: "Sophia Johnson",
    rating: "5",
    comment: "An absolutely amazing experience! Everything exceeded expectations.",
    profileImage: require("../assets/images/dataImages/reviews/sophiaJohnson.png"),
  },
  {
    id: 2,
    name: "Liam Brown",
    rating: "4",
    comment: "Great atmosphere and plenty of fun activities.",
    profileImage: require("../assets/images/dataImages/reviews/liamBrown.png"),
  },
  {
    id: 3,
    name: "Noah Wilson",
    rating: "5",
    comment: "Best experience ever! Everything was thrilling and well worth it.",
    profileImage: require("../assets/images/dataImages/reviews/noahWilson.png"),
  },
  {
    id: 4,
    name: "Olivia Moore",
    rating: "4",
    comment: "We had a great time. The staff was very accommodating and friendly.",
    profileImage: require("../assets/images/dataImages/reviews/oliviaMoore.png"),
  },
  {
    id: 5,
    name: "Ava Anderson",
    rating: "5",
    comment: "Such a magical experience! Everything was well-organized and enjoyable.",
    profileImage: require("../assets/images/dataImages/reviews/avaAnderson.png"),
  },
  {
    id: 6,
    name: "Isabella Thompson",
    rating: "4",
    comment: "Very enjoyable experience! A lot of unique attractions to explore.",
    profileImage: require("../assets/images/dataImages/reviews/isabellaThompson.png"),
  },
  {
    id: 7,
    name: "Mia Harris",
    rating: "5",
    comment: "An unforgettable day! Everything was fantastic, can't wait to return.",
    profileImage: require("../assets/images/dataImages/reviews/miaHarris.png"),
  },
  {
    id: 8,
    name: "Benjamin Clark",
    rating: "4",
    comment: "Nice place with plenty to see and do. A wonderful day out.",
    profileImage: require("../assets/images/dataImages/reviews/benjaminClark.png"),
  },
  {
    id: 9,
    name: "Charlotte Lewis",
    rating: "5",
    comment: "We loved every minute! The staff was amazing and everything was perfect.",
    profileImage: require("../assets/images/dataImages/reviews/charlotteLewis.png"),
  },
  {
    id: 10,
    name: "Amelia Hall",
    rating: "4",
    comment: "A fun day out! Everything was very enjoyable.",
    profileImage: require("../assets/images/dataImages/reviews/ameliaHall.png"),
  },
  {
    id: 11,
    name: "Harper Young",
    rating: "5",
    comment: "A magical place! We enjoyed every moment and will definitely return.",
    profileImage: require("../assets/images/dataImages/reviews/harperYoung.png"),
  },
  {
    id: 12,
    name: "Henry Hernandez",
    rating: "4",
    comment: "Good variety of attractions. A perfect place for a weekend getaway.",
    profileImage: require("../assets/images/dataImages/reviews/henryHernandez.png"),
  },
  {
    id: 13,
    name: "Evelyn King",
    rating: "5",
    comment: "A perfect day out! Everything was fantastic, from start to finish.",
    profileImage: require("../assets/images/dataImages/reviews/evelynKing.png"),
  },
  {
    id: 14,
    name: "Ella Lopez",
    rating: "5",
    comment: "Loved the atmosphere! It felt like stepping into another world.",
    profileImage: require("../assets/images/dataImages/reviews/ellaLopez.png"),
  },
];
